Development
Intelligenstia-PBR/GraceShopper pull request #47
Opened 2023-08-23 23:23 UTC by sehalondas

2023-08-28 22:39 UTC, parisyee requested changes
Not too shabby! Just curious about those few comments. But in general, this looks great!

2023-08-28 22:39 UTC, parisyee commented on api/orders.js
> +router.get("/", async (req, res, next) => {
I notice that these routes are all prefixed with `/orders`, but does that mean this from api/index.js doesn't tack the `/orders` on to the front of the path?
```
const ordersRouter = require("./orders");
router.use("/orders", ordersRouter);
```
It's not clear to me why this route would be different than the others in this file.

2023-08-28 22:39 UTC, parisyee commented on api/orders.js
> +            });
You'll want the response to include a 404 code for not found

2023-08-28 22:39 UTC, parisyee commented on api/orders.js
> +router.get("/order/:userId", async (req, res, next) => {
why is `order` singular? What if a user had multiple?

2023-08-28 22:39 UTC, parisyee commented on api/orders.js
> +router.patch("/orders/:productId", async (req, res, next) => {
Why are you putting this behavior in the `orders` namespace? Seems like a product concern, no?

2023-08-28 22:39 UTC, parisyee commented on api/products.js
> +      });
Same thing for these... send response codes.

2023-08-28 22:39 UTC, parisyee commented on db/models/products.js
> +      WHERE title
don't you want `searchTerm`?

2023-08-30 23:51 UTC, leafoflegend requested changes
I like how far the front end has come along! The database has some pretty serious issues relating to the models - you may need to rethink some of whats going on there. Need a pretty big push on the backend here as well as the frontend.

Theres also not even a vague concept of security on the backend. Absolutely everything is vulnerable.

2023-08-30 23:51 UTC, leafoflegend commented on README.md
> +# Project Goals
Love the use of markdown!

2023-08-30 23:51 UTC, leafoflegend commented on api/orders.js
> +router.get("/order/:userId", async (req, res, next) => {
I might even argue this feels slightly inverted to me as well. Like, orders belong to a user, not users belong to orders. I might do this route over on the user side.

2023-08-30 23:51 UTC, leafoflegend commented on api/utils.js
> +      next();
This isn't security, this is a stub. I hope theres intentions to actually inspect this header and validate its something meaningful? As of right now, every route is a security vulnerability.

2023-08-30 23:51 UTC, leafoflegend commented on db/seedData.js
> +        "productId" INTEGER REFERENCES products(id),
Don't many products belong to a single order? This infers only one does.

2023-08-30 23:51 UTC, leafoflegend commented on src/components/App.jsx
> +// This is the Mother of all components. This is what will house all of the other components to render on screen.
👍

2023-08-30 23:51 UTC, leafoflegend commented on src/components/Body/AllProducts.jsx
> +  };
Nice!

2023-08-30 23:51 UTC, leafoflegend commented on src/components/Header/Header.jsx
> +              </>
Do you need `href`s on these? Not sure they're totally valid.

2023-09-07 02:17 UTC, merged